config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :chatrooms
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
# frozen_string_literal: true

class Chatroom < ApplicationRecord
  has_many :messages
  has_many :users, through: :messages

  validates :topic, presence: true, uniqueness: { case_sensitive: false }
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :messages
  has_many :chatrooms, through: :messages

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_sign_up_params, if: :devise_controller?

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username])
  end
end

app/controllers/chatrooms_controller.rb
# frozen_string_literal: true

class ChatroomsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_chatroom, only: %i[show destroy]

  def index
    @chatrooms = Chatroom.all.order(topic: :asc)
  end

  def show
    @message = Message.new
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    chatroom = Chatroom.new(chatroom_params)
    if chatroom.save
      respond_to do |format|
        format.html { redirect_to chatroom, notice: 'Chatroom created' }
        format.json { head :ok, status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new, alert: 'Something went wrong' }
        format.json { render json: chatroom.errors, status: :unprocessible_entity }
      end
    end
  end

  private

  def find_chatroom
    @chatroom = Chatroom.find_by(slug: params[:slug])
  end

  def chatroom_params
    params.require(:chatroom).permit(:topic)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/index.html.erb
<% @chatrooms.each do |chatroom| %>
  <%= link_to chatroom.topic, chatroom_path(chatroom) %>
<% end %>

app/views/chatrooms/new.html.erb
<h1>Create a chatroom</h1>

<%= simple_form_for @chatroom do |f| %>
  <%= f.input :topic, required: true, placeholder: 'Name your chatroom' %>
  <%= f.button :submit, 'Create chatroom' %>
<% end %>

app/views/chatrooms/show.html.erb
<h1><%= @chatroom.topic %></h1>
<% @chatroom.messages.each do |message| %>
  <div class="message">
    <span> <%= message.user.username %> </span>
    <span> <%= message.content %> </span>
  </div>
<% end %>

<%= simple_form_for @message do |f| %>
  <%= f.input :content, required: true %>
  <%= f.input :chatroom_id, input_html: { value: @chatroom.id }, as: :hidden %>
  <%= f.input :user_id, input_html: { value: current_user.id }, as: :hidden %>
  <%= f.button :submit, 'Send Message' %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionCableExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>